server:
  port: 8070
  servlet:
    context-path: /pleiades/api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/portal
    username: vtw
    password: vtw123#
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: blindprayer
      password: 30539w
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
# Apache Camel
camel:
  springboot:
    main-run-controller: true
    stream-caching-enabled: false
    jmx-enabled: false
  component:
    kafka:
      allow-manual-commit: true
      auto-commit-enable: false
      shutdown-timeout: 10
      brokers: 34.64.142.187:9092
      group-id: test-001
      break-on-first-error: true
logging:
  level:
    root: info
    '[org.hibernate.type]': trace
    '[com.vtw]': debug